# Generated by Django 2.1 on 2019-03-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_auto_20190316_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_words',
            name='Antonyms',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='daily_words',
            name='Synonyms',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='daily_words',
            name='Word',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
