# Generated by Django 2.1 on 2019-03-17 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_auto_20190316_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_words',
            old_name='examples',
            new_name='Examples',
        ),
    ]
