# Generated by Django 2.2.1 on 2019-07-28 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0004_auto_20190317_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daily_words',
            options={'ordering': ['-Date_posted']},
        ),
    ]
